/* Oi-Qaragai — mock data (structured for future Strapi swap) */
export const OQ = {
  contacts: {
    phone: '+7 727 000 00 00',
    insta: '@oiqaragai',
    weather: '−4°C',
    address: 'Алматинская область, ущелье Ой-Карагай',
    email: 'hello@oiqaragai.kz',
  },

  mega: [
    {
      key: 'hotels',
      title: 'Отели',
      icon: 'bed',
      items: [
        'Шале «Терренкур»',
        'Отель Pine Peak',
        'Глэмпинг «Хвоя»',
        'Апарт-резиденция',
        'Домики у озера',
      ],
      more: 'Все варианты размещения',
    },
    {
      key: 'fun',
      title: 'Развлечения',
      icon: 'ski',
      items: [
        'Горные лыжи и сноуборд',
        'Сноупарк',
        'Зиплайн над ущельем',
        'Каток под открытым небом',
        'Тюбинг-трассы',
        'Прокат снаряжения',
      ],
      more: 'Все активности',
    },
    {
      key: 'rest',
      title: 'Рестораны',
      icon: 'fork',
      items: [
        '«Очаг» · гриль-бар',
        '«Хвоя» · авторская кухня',
        'Паб «Панорама»',
        'Чайхана',
        'Кофейня Vershina',
      ],
      more: 'Все рестораны',
    },
    {
      key: 'spa',
      title: 'SPA и Баня',
      icon: 'spa',
      items: [
        'Кедровая баня',
        'Хаммам',
        'Финская сауна',
        'SPA-уходы',
        'Бассейн с подогревом',
      ],
      more: 'Все услуги SPA',
    },
    {
      key: 'events',
      title: 'Мероприятия',
      icon: 'star',
      items: [
        'Афиша событий',
        'Новый год в горах',
        'Свадьбы',
        'Концерты',
        'Прошедшие события',
      ],
      more: 'Вся афиша',
    },
    {
      key: 'biz',
      title: 'Для бизнеса',
      icon: 'briefcase',
      items: [
        'MICE / Конференции',
        'Тимбилдинг',
        'Калькулятор мероприятия',
        'Кейтеринг',
        'MICE-каталог (PDF)',
      ],
      more: 'Возможности курорта',
    },
  ],

  quick: [
    { t: 'Проживание', d: '12 объектов', icon: 'bed' },
    { t: 'Рестораны', d: '5 заведений', icon: 'fork' },
    { t: 'Активности', d: 'круглый год', icon: 'ski' },
    { t: 'Веб-камеры', d: '6 трансляций', icon: 'camera' },
    { t: '3D-тур', d: 'карта курорта', icon: 'cube' },
  ],

  offers: [
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/766b42f1e7f3533af60e997a726f61d5.jpg',
      badge: '−20%',
      badgeType: 'accent',
      tag: 'Пакет',
      title: 'Зимний weekend',
      desc: '2 ночи в шале, завтраки и ски-пасс на оба дня. Для двоих.',
      price: '78 000',
      per: 'за 2 ночи',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/916bea98e22577b9ecff5c2fc98c7f46.jpg',
      badge: 'SPA',
      badgeType: 'dark',
      tag: 'Релакс',
      title: 'SPA-день для двоих',
      desc: 'Кедровая баня, хаммам, массаж и бассейн с видом на горы.',
      price: '45 000',
      per: 'за визит',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/00251d3dfb96c7ec69bcacaea04e83c4.jpg',
      badge: '−15%',
      badgeType: 'accent',
      tag: 'Ски-пасс',
      title: 'Ски-пасс на 3 дня',
      desc: 'Безлимитный доступ ко всем подъёмникам и трассам курорта.',
      price: '32 000',
      per: '3 дня',
      cta: 'Купить',
    },
  ],

  things: [
    {
      type: 'Отели',
      typeLabel: 'Отель',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/624e0b4b4e408bcd06cc361ac97272d7.jpg',
      title: 'Шале «Терренкур»',
      desc: 'Премиальные шале с камином, панорамным остеклением и личной террасой.',
      meta: [
        { ic: 'star', t: '4.9' },
        { ic: 'user', t: 'до 6 гостей' },
      ],
      price: '95 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      type: 'Отели',
      typeLabel: 'Отель',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e87983b27c8a754c2306e9bf7ff4661d.jpg',
      title: 'Отель Pine Peak',
      desc: 'Уютные номера в главном корпусе, в шаге от подъёмника и ресторанов.',
      meta: [
        { ic: 'star', t: '4.7' },
        { ic: 'user', t: '2–4 гостя' },
      ],
      price: '64 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9071cbfefc312116cb40b7c770e05063.jpg',
      title: '«Очаг» · Гриль-бар',
      desc: 'Мясо на открытом огне, локальные специалитеты и горячий глинтвейн.',
      meta: [
        { ic: 'clock', t: '12:00–24:00' },
        { ic: 'fork', t: 'Гриль' },
      ],
      cta: 'Меню',
    },
    {
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9e0626703298e0306cf381c539b25d8e.jpeg',
      title: '«Хвоя» · Авторская кухня',
      desc: 'Сет-меню от шефа из сезонных продуктов Тянь-Шаня. Панорамный зал.',
      meta: [
        { ic: 'clock', t: '10:00–23:00' },
        { ic: 'star', t: '4.8' },
      ],
      cta: 'Меню',
    },
    {
      type: 'Развлечения',
      typeLabel: 'Активность',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/be9de408fd6866bd1150c6b786569c94.jpg',
      title: 'Горные лыжи · Ски-пасс',
      desc: '18 км трасс всех уровней, ночное катание и школа инструкторов.',
      meta: [
        { ic: 'clock', t: '09:00–22:00' },
        { ic: 'ski', t: '6 трасс' },
      ],
      price: '12 000',
      per: 'день',
      cta: 'Купить',
    },
    {
      type: 'Развлечения',
      typeLabel: 'Активность',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/dc09954344ceef7c8730400ad93dd82d.jpg',
      title: 'Зиплайн над ущельем',
      desc: '800 метров полёта над зимним лесом со скоростью до 70 км/ч.',
      meta: [
        { ic: 'user', t: 'от 12 лет' },
        { ic: 'clock', t: '10:00–18:00' },
      ],
      price: '9 000',
      per: 'билет',
      cta: 'Купить',
    },
    {
      type: 'SPA',
      typeLabel: 'SPA и Баня',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e2245f60b098f59536e15c3d431a7386.jpeg',
      title: 'Кедровая баня',
      desc: 'Парение на пихтовых вениках, травяной чай и купель с горной водой.',
      meta: [
        { ic: 'clock', t: 'по записи' },
        { ic: 'user', t: 'до 8 чел.' },
      ],
      price: '25 000',
      per: '2 часа',
      cta: 'Купить',
    },
    {
      type: 'SPA',
      typeLabel: 'SPA и Баня',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/7fa7a1cdaa60112376a1aa35123825ce.jpg',
      title: 'SPA-ритуал «Тянь-Шань»',
      desc: '90 минут: скраб, обёртывание и массаж с маслами горных трав.',
      meta: [
        { ic: 'clock', t: '90 мин' },
        { ic: 'star', t: '4.9' },
      ],
      price: '38 000',
      per: 'визит',
      cta: 'Купить',
    },
  ],

  gallery: [
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/624e0b4b4e408bcd06cc361ac97272d7.jpg', cap: 'Подъёмник на рассвете', tall: true },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e87983b27c8a754c2306e9bf7ff4661d.jpg', cap: 'Закат над хребтом' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/672781f715c9dfff7e6f26a11daef8b6.jpg', cap: 'Снежные вершины' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/35cbcb290585a502aa92f013e08e63f4.jpg', cap: 'Хвойный лес' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/0804ee613beaed6769b1f1cc114b6c49.jpg', cap: 'Утро в долине' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/21b9d22819c9d8ba4706a448d9ce6ea2.jpeg', cap: 'Звёздная ночь', tall: true },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f86b7ca3f7e98d67458984dc8c5c7a12.jpg', cap: 'Тёплый свет шале' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/7f023cdfe0db3b829a3434065a344d78.jpg', cap: 'Гриль у костра' },
  ],

  rules: [
    {
      title: 'Регистрация и заезд',
      body: 'Заезд с 14:00, выезд до 12:00. При заселении необходим документ, удостоверяющий личность. Ранний заезд и поздний выезд — по предварительному запросу и при наличии свободных номеров.',
    },
    {
      title: 'Безопасность на склонах',
      body: 'Катание разрешено только на подготовленных трассах в рабочие часы подъёмников. Шлем обязателен для детей до 14 лет и рекомендован всем гостям. Следуйте указателям и сигналам службы спасения курорта.',
    },
    {
      title: 'Прокат снаряжения',
      body: 'Прокат лыж, сноубордов и защиты доступен у нижней станции с 08:30. Залог оформляется картой или наличными. Снаряжение необходимо вернуть в день окончания аренды до 22:00.',
    },
    {
      title: 'Размещение с животными',
      body: 'Мы рады гостям с питомцами в отдельных шале категории Pet-friendly. Необходимо предупредить администратора при бронировании. На территории действует правило выгула на поводке.',
    },
    {
      title: 'Парковка и трансфер',
      body: 'Бесплатная гостевая парковка расположена у въезда на курорт. Трансфер от Алматы и обратно доступен по расписанию — бронируйте место заранее на стойке размещения или по телефону.',
    },
  ],

  partners: ['KASPI', 'Visa', 'Air Astana', 'Beeline', 'Halyk', 'Almaty'],
};
