/* Oi-Qaragai — mock data (structured for future Strapi swap) */
export const OQ = {
  contacts: {
    phone: '+7 727 000 00 00',
    insta: '@oiqaragai',
    instaUrl: 'https://www.instagram.com/oiqaragai/',
    weather: '−4°C',
    address: 'Алматинская область, ущелье Ой-Карагай',
    email: 'hello@oiqaragai.kz',
  },

  app: {
    screenshots: [
      {
        src: 'https://oq-prod.storage.yandexcloud.kz/media-test/ddfe930402657241d67d1a1bb8df9f74.png',
        alt: 'Карта и поиск в приложении Oi-Qaragai',
      },
      {
        src: 'https://oq-prod.storage.yandexcloud.kz/media-test/b4df8c0b866314d81c1a46bd7363f236.png',
        alt: 'SkiPass и сервисы в приложении Oi-Qaragai',
      },
    ],
  },

  weather: {
    city: {
      name: 'Алматы',
      temp: '−2°C',
      condition: 'Облачно',
      wind: '4 м/с',
      humidity: '68%',
    },
    resort: {
      name: 'Курорт',
      temp: '−4°C',
      condition: 'Ясно',
      wind: '6 м/с',
      humidity: '54%',
      open: true,
      lifts: '12/14',
      slopes: '18/22',
    },
    forecast: [
      { day: 'Сегодня', city: '−2°', resort: '−4°', icon: 'cloud' },
      { day: 'Чт', city: '−1°', resort: '−3°', icon: 'sun' },
      { day: 'Пт', city: '0°', resort: '−2°', icon: 'sun' },
      { day: 'Сб', city: '−3°', resort: '−6°', icon: 'cloud' },
      { day: 'Вс', city: '−4°', resort: '−7°', icon: 'cloud' },
      { day: 'Пн', city: '−2°', resort: '−5°', icon: 'sun' },
      { day: 'Вт', city: '−1°', resort: '−4°', icon: 'sun' },
    ],
  },

  mega: [
    {
      key: 'hotels',
      title: 'Отели',
      icon: 'bed',
      items: [
        'Шале «Терренкур»',
        'Отель Pine Peak',
        'Глэмпинг «Хвоя»',
        'Апарт-резиденция',
        'Домики у озера',
      ],
      more: 'Все варианты размещения',
    },
    {
      key: 'fun',
      title: 'Развлечения',
      icon: 'ski',
      items: [
        'Горные лыжи и сноуборд',
        'Сноупарк',
        'Зиплайн над ущельем',
        'Каток под открытым небом',
        'Тюбинг-трассы',
        'Прокат снаряжения',
      ],
      more: 'Все активности',
    },
    {
      key: 'rest',
      title: 'Рестораны',
      icon: 'fork',
      items: [
        '«Очаг» · гриль-бар',
        '«Хвоя» · авторская кухня',
        'Паб «Панорама»',
        'Чайхана',
        'Кофейня Vershina',
      ],
      more: 'Все рестораны',
    },
    {
      key: 'spa',
      title: 'SPA и Баня',
      icon: 'spa',
      items: [
        'Кедровая баня',
        'Хаммам',
        'Финская сауна',
        'SPA-уходы',
        'Бассейн с подогревом',
      ],
      more: 'Все услуги SPA',
    },
    {
      key: 'events',
      title: 'Мероприятия',
      icon: 'star',
      items: [
        'Афиша событий',
        'Новый год в горах',
        'Свадьбы',
        'Концерты',
        'Прошедшие события',
      ],
      more: 'Вся афиша',
    },
    {
      key: 'biz',
      title: 'Для бизнеса',
      icon: 'briefcase',
      items: [
        'MICE / Конференции',
        'Тимбилдинг',
        'Калькулятор мероприятия',
        'Кейтеринг',
        'MICE-каталог (PDF)',
      ],
      more: 'Возможности курорта',
    },
  ],

  quick: [
    { t: 'Проживание', d: '12 объектов', icon: 'bed', href: '/guide' },
    { t: 'Рестораны', d: '5 заведений', icon: 'fork', href: '/guide' },
    { t: 'Активности', d: 'круглый год', icon: 'ski', href: '/guide' },
    { t: 'Веб-камеры', d: '6 трансляций', icon: 'camera', href: '#' },
    { t: '3D-тур', d: 'карта курорта', icon: 'cube', href: '#' },
  ],

  hero: {
    slides: [
      {
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e94707741a500180a04f7678d1fc84cb.jpg',
        title: 'Проживание',
        detail: '12 объектов · от шале до глэмпинга',
        href: '/guide',
      },
      {
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/a60880837954b3f599fa9bf993e716bd.jpg',
        title: 'Активности',
        detail: 'лыжи, зиплайн, тюбинг круглый год',
        href: '/guide',
      },
      {
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/bee8fe2a4da6225678175d7f4c8a15ae.jpg',
        title: 'Рестораны и SPA',
        detail: '5 заведений · кедровая баня и хаммам',
        href: '/guide',
      },
    ],
    interval: 5500,
  },

  offers: [
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/766b42f1e7f3533af60e997a726f61d5.jpg',
      badge: '−20%',
      badgeType: 'accent',
      tag: 'Пакет',
      title: 'Зимний weekend',
      desc: '2 ночи в шале, завтраки и ски-пасс на оба дня. Для двоих.',
      price: '78 000',
      per: 'за 2 ночи',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/916bea98e22577b9ecff5c2fc98c7f46.jpg',
      badge: 'SPA',
      badgeType: 'dark',
      tag: 'Релакс',
      title: 'SPA-день для двоих',
      desc: 'Кедровая баня, хаммам, массаж и бассейн с видом на горы.',
      price: '45 000',
      per: 'за визит',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/00251d3dfb96c7ec69bcacaea04e83c4.jpg',
      badge: '−15%',
      badgeType: 'accent',
      tag: 'Ски-пасс',
      title: 'Ски-пасс на 3 дня',
      desc: 'Безлимитный доступ ко всем подъёмникам и трассам курорта.',
      price: '32 000',
      per: '3 дня',
      cta: 'Купить',
    },
  ],

  things: [
    {
      id: 'terrenkur',
      type: 'Отели',
      typeLabel: 'Отель',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/624e0b4b4e408bcd06cc361ac97272d7.jpg',
      title: 'Шале «Терренкур»',
      desc: 'Премиальные шале с камином, панорамным остеклением и личной террасой.',
      meta: [
        { ic: 'star', t: '4.9' },
        { ic: 'user', t: 'до 6 гостей' },
      ],
      price: '95 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      id: 'pine-peak',
      type: 'Отели',
      typeLabel: 'Отель',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e87983b27c8a754c2306e9bf7ff4661d.jpg',
      title: 'Отель Pine Peak',
      desc: 'Уютные номера в главном корпусе, в шаге от подъёмника и ресторанов.',
      meta: [
        { ic: 'star', t: '4.7' },
        { ic: 'user', t: '2–4 гостя' },
      ],
      price: '64 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      id: 'ochag',
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9071cbfefc312116cb40b7c770e05063.jpg',
      title: '«Очаг» · Гриль-бар',
      desc: 'Мясо на открытом огне, локальные специалитеты и горячий глинтвейн.',
      meta: [
        { ic: 'clock', t: '12:00–24:00' },
        { ic: 'fork', t: 'Гриль' },
      ],
      cta: 'Меню',
    },
    {
      id: 'hvoya',
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9e0626703298e0306cf381c539b25d8e.jpeg',
      title: '«Хвоя» · Авторская кухня',
      desc: 'Сет-меню от шефа из сезонных продуктов Тянь-Шаня. Панорамный зал.',
      meta: [
        { ic: 'clock', t: '10:00–23:00' },
        { ic: 'star', t: '4.8' },
      ],
      cta: 'Меню',
    },
    {
      id: 'ski-pass',
      type: 'Развлечения',
      typeLabel: 'Активность',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/be9de408fd6866bd1150c6b786569c94.jpg',
      title: 'Горные лыжи · Ски-пасс',
      desc: '18 км трасс всех уровней, ночное катание и школа инструкторов.',
      meta: [
        { ic: 'clock', t: '09:00–22:00' },
        { ic: 'ski', t: '6 трасс' },
      ],
      price: '12 000',
      per: 'день',
      cta: 'Купить',
    },
    {
      id: 'zipline',
      type: 'Развлечения',
      typeLabel: 'Активность',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/dc09954344ceef7c8730400ad93dd82d.jpg',
      title: 'Зиплайн над ущельем',
      desc: '800 метров полёта над зимним лесом со скоростью до 70 км/ч.',
      meta: [
        { ic: 'user', t: 'от 12 лет' },
        { ic: 'clock', t: '10:00–18:00' },
      ],
      price: '9 000',
      per: 'билет',
      cta: 'Купить',
    },
    {
      id: 'cedar-bath',
      type: 'SPA',
      typeLabel: 'SPA и Баня',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e2245f60b098f59536e15c3d431a7386.jpeg',
      title: 'Кедровая баня',
      desc: 'Парение на пихтовых вениках, травяной чай и купель с горной водой.',
      meta: [
        { ic: 'clock', t: 'по записи' },
        { ic: 'user', t: 'до 8 чел.' },
      ],
      price: '25 000',
      per: '2 часа',
      cta: 'Купить',
    },
    {
      id: 'tianshan-ritual',
      type: 'SPA',
      typeLabel: 'SPA и Баня',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/7fa7a1cdaa60112376a1aa35123825ce.jpg',
      title: 'SPA-ритуал «Тянь-Шань»',
      desc: '90 минут: скраб, обёртывание и массаж с маслами горных трав.',
      meta: [
        { ic: 'clock', t: '90 мин' },
        { ic: 'star', t: '4.9' },
      ],
      price: '38 000',
      per: 'визит',
      cta: 'Купить',
    },
  ],

  gallery: [
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/624e0b4b4e408bcd06cc361ac97272d7.jpg', cap: 'Подъёмник на рассвете', tall: true },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e87983b27c8a754c2306e9bf7ff4661d.jpg', cap: 'Закат над хребтом' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/672781f715c9dfff7e6f26a11daef8b6.jpg', cap: 'Снежные вершины' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/35cbcb290585a502aa92f013e08e63f4.jpg', cap: 'Хвойный лес' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/0804ee613beaed6769b1f1cc114b6c49.jpg', cap: 'Утро в долине' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/21b9d22819c9d8ba4706a448d9ce6ea2.jpeg', cap: 'Звёздная ночь', tall: true },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f86b7ca3f7e98d67458984dc8c5c7a12.jpg', cap: 'Тёплый свет шале' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/7f023cdfe0db3b829a3434065a344d78.jpg', cap: 'Гриль у костра' },
  ],

  rules: [
    {
      title: 'Регистрация и заезд',
      body: 'Заезд с 14:00, выезд до 12:00. При заселении необходим документ, удостоверяющий личность. Ранний заезд и поздний выезд — по предварительному запросу и при наличии свободных номеров.',
    },
    {
      title: 'Безопасность на склонах',
      body: 'Катание разрешено только на подготовленных трассах в рабочие часы подъёмников. Шлем обязателен для детей до 14 лет и рекомендован всем гостям. Следуйте указателям и сигналам службы спасения курорта.',
    },
    {
      title: 'Прокат снаряжения',
      body: 'Прокат лыж, сноубордов и защиты доступен у нижней станции с 08:30. Залог оформляется картой или наличными. Снаряжение необходимо вернуть в день окончания аренды до 22:00.',
    },
    {
      title: 'Размещение с животными',
      body: 'Мы рады гостям с питомцами в отдельных шале категории Pet-friendly. Необходимо предупредить администратора при бронировании. На территории действует правило выгула на поводке.',
    },
    {
      title: 'Парковка и трансфер',
      body: 'Бесплатная гостевая парковка расположена у въезда на курорт. Трансфер от Алматы и обратно доступен по расписанию — бронируйте место заранее на стойке размещения или по телефону.',
    },
  ],

  partners: ['KASPI', 'Visa', 'Air Astana', 'Beeline', 'Halyk', 'Almaty'],

  offersAll: [
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/766b42f1e7f3533af60e997a726f61d5.jpg',
      badge: '−20%',
      badgeType: 'accent',
      tag: 'Пакет',
      category: 'Пакеты',
      title: 'Зимний weekend',
      desc: '2 ночи в шале, завтраки и ски-пасс на оба дня. Для двоих.',
      price: '78 000',
      per: 'за 2 ночи',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/916bea98e22577b9ecff5c2fc98c7f46.jpg',
      badge: 'SPA',
      badgeType: 'dark',
      tag: 'Релакс',
      category: 'SPA',
      title: 'SPA-день для двоих',
      desc: 'Кедровая баня, хаммам, массаж и бассейн с видом на горы.',
      price: '45 000',
      per: 'за визит',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/00251d3dfb96c7ec69bcacaea04e83c4.jpg',
      badge: '−15%',
      badgeType: 'accent',
      tag: 'Ски-пасс',
      category: 'Ски-пасс',
      title: 'Ски-пасс на 3 дня',
      desc: 'Безлимитный доступ ко всем подъёмникам и трассам курорта.',
      price: '32 000',
      per: '3 дня',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e87983b27c8a754c2306e9bf7ff4661d.jpg',
      badge: 'Новинка',
      badgeType: 'dark',
      tag: 'Пакет',
      category: 'Пакеты',
      title: 'Семейные каникулы',
      desc: '3 ночи, детский ски-пасс и ужин в ресторане «Очаг» для семьи из 4 человек.',
      price: '142 000',
      per: 'за 3 ночи',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e2245f60b098f59536e15c3d431a7386.jpeg',
      badge: '−10%',
      badgeType: 'accent',
      tag: 'SPA',
      category: 'SPA',
      title: 'Банный ритуал «Хвоя»',
      desc: 'Кедровый пар, контрастные купели и травяной чай в приватной зоне.',
      price: '28 000',
      per: '2 часа',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/be9de408fd6866bd1150c6b786569c94.jpg',
      badge: 'Хит',
      badgeType: 'dark',
      tag: 'Ски-пасс',
      category: 'Ски-пасс',
      title: 'Дневной ски-пасс',
      desc: 'Полный день на склонах: 6 трасс, сноупарк и вечернее катание по пятницам.',
      price: '12 000',
      per: 'день',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9071cbfefc312116cb40b7c770e05063.jpg',
      badge: 'Ужин',
      badgeType: 'dark',
      tag: 'Ресторан',
      category: 'Пакеты',
      title: 'Гастро-вечер в «Очаге»',
      desc: 'Сет от шефа, винная пара и трансфер от шале до ресторана и обратно.',
      price: '34 000',
      per: 'на двоих',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/624e0b4b4e408bcd06cc361ac97272d7.jpg',
      badge: '−25%',
      badgeType: 'accent',
      tag: 'Пакет',
      category: 'Пакеты',
      title: 'Романтика в шале',
      desc: 'Ночь в премиальном шале, завтрак в номер и SPA-набор для двоих.',
      price: '98 000',
      per: 'за ночь',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/dc09954344ceef7c8730400ad93dd82d.jpg',
      badge: 'Адреналин',
      badgeType: 'dark',
      tag: 'Активность',
      category: 'Активности',
      title: 'Зиплайн + тюбинг',
      desc: 'Комбо-билет: полёт над ущельем и 2 часа на тюбинг-трассе.',
      price: '14 500',
      per: 'билет',
      cta: 'Купить',
    },
  ],

  mapZones: [
    { id: 'all', label: 'Весь курорт', icon: 'cube', x: 50, y: 50 },
    { id: 'hotels', label: 'Проживание', icon: 'bed', x: 28, y: 62 },
    { id: 'rest', label: 'Рестораны', icon: 'fork', x: 58, y: 38 },
    { id: 'fun', label: 'Активности', icon: 'ski', x: 72, y: 58 },
    { id: 'spa', label: 'SPA и баня', icon: 'spa', x: 42, y: 28 },
  ],

  thingsAll: [
    {
      id: 'terrenkur',
      type: 'Отели',
      typeLabel: 'Отель',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/624e0b4b4e408bcd06cc361ac97272d7.jpg',
      title: 'Шале «Терренкур»',
      desc: 'Премиальные шале с камином, панорамным остеклением и личной террасой.',
      meta: [{ ic: 'star', t: '4.9' }, { ic: 'user', t: 'до 6 гостей' }],
      price: '95 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      id: 'pine-peak',
      type: 'Отели',
      typeLabel: 'Отель',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e87983b27c8a754c2306e9bf7ff4661d.jpg',
      title: 'Отель Pine Peak',
      desc: 'Уютные номера в главном корпусе, в шаге от подъёмника и ресторанов.',
      meta: [{ ic: 'star', t: '4.7' }, { ic: 'user', t: '2–4 гостя' }],
      price: '64 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      type: 'Отели',
      typeLabel: 'Глэмпинг',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e94707741a500180a04f7678d1fc84cb.jpg',
      title: 'Глэмпинг «Хвоя»',
      desc: 'Купола с видом на хребет, отопление и завтрак с локальными продуктами.',
      meta: [{ ic: 'star', t: '4.8' }, { ic: 'user', t: '2 гостя' }],
      price: '52 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      type: 'Отели',
      typeLabel: 'Глэмпинг',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e94707741a500180a04f7678d1fc84cb.jpg',
      title: 'Глэмпинг «Хвоя»',
      desc: 'Купола с видом на хребет, отопление и завтрак с локальными продуктами.',
      meta: [{ ic: 'star', t: '4.8' }, { ic: 'user', t: '2 гостя' }],
      price: '52 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      id: 'glamping-hvoya',
      type: 'Отели',
      typeLabel: 'Глэмпинг',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e94707741a500180a04f7678d1fc84cb.jpg',
      title: 'Глэмпинг «Хвоя»',
      desc: 'Купола с видом на хребет, отопление и завтрак с локальными продуктами.',
      meta: [{ ic: 'star', t: '4.8' }, { ic: 'user', t: '2 гостя' }],
      price: '52 000',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      id: 'ochag',
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      zone: 'rest',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9071cbfefc312116cb40b7c770e05063.jpg',
      title: '«Очаг» · Гриль-бар',
      desc: 'Мясо на открытом огне, локальные специалитеты и горячий глинтвейн.',
      meta: [{ ic: 'clock', t: '12:00–24:00' }, { ic: 'fork', t: 'Гриль' }],
      cta: 'Меню',
    },
    {
      id: 'hvoya',
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      zone: 'rest',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9e0626703298e0306cf381c539b25d8e.jpeg',
      title: '«Хвоя» · Авторская кухня',
      desc: 'Сет-меню от шефа из сезонных продуктов Тянь-Шаня. Панорамный зал.',
      meta: [{ ic: 'clock', t: '10:00–23:00' }, { ic: 'star', t: '4.8' }],
      cta: 'Меню',
    },
    {
      id: 'panorama',
      type: 'Рестораны',
      typeLabel: 'Паб',
      zone: 'rest',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/bee8fe2a4da6225678175d7f4c8a15ae.jpg',
      title: 'Паб «Панорама»',
      desc: 'Крафт, сытные закуски и живая музыка по выходным.',
      meta: [{ ic: 'clock', t: '16:00–02:00' }],
      cta: 'Меню',
    },
    {
      id: 'ski-pass',
      type: 'Развлечения',
      typeLabel: 'Активность',
      zone: 'fun',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/be9de408fd6866bd1150c6b786569c94.jpg',
      title: 'Горные лыжи · Ски-пасс',
      desc: '18 км трасс всех уровней, ночное катание и школа инструкторов.',
      meta: [{ ic: 'clock', t: '09:00–22:00' }, { ic: 'ski', t: '6 трасс' }],
      price: '12 000',
      per: 'день',
      cta: 'Купить',
    },
    {
      id: 'zipline',
      type: 'Развлечения',
      typeLabel: 'Активность',
      zone: 'fun',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/dc09954344ceef7c8730400ad93dd82d.jpg',
      title: 'Зиплайн над ущельем',
      desc: '800 метров полёта над зимним лесом со скоростью до 70 км/ч.',
      meta: [{ ic: 'user', t: 'от 12 лет' }, { ic: 'clock', t: '10:00–18:00' }],
      price: '9 000',
      per: 'билет',
      cta: 'Купить',
    },
    {
      id: 'tubing',
      type: 'Развлечения',
      typeLabel: 'Активность',
      zone: 'fun',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/a60880837954b3f599fa9bf993e716bd.jpg',
      title: 'Тюбинг-трасса',
      desc: 'Семейная трасса с подъёмником и вечерней подсветкой.',
      meta: [{ ic: 'clock', t: '10:00–20:00' }],
      price: '4 500',
      per: 'час',
      cta: 'Купить',
    },
    {
      id: 'cedar-bath',
      type: 'SPA',
      typeLabel: 'SPA и Баня',
      zone: 'spa',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e2245f60b098f59536e15c3d431a7386.jpeg',
      title: 'Кедровая баня',
      desc: 'Парение на пихтовых вениках, травяной чай и купель с горной водой.',
      meta: [{ ic: 'clock', t: 'по записи' }, { ic: 'user', t: 'до 8 чел.' }],
      price: '25 000',
      per: '2 часа',
      cta: 'Купить',
    },
    {
      id: 'tianshan-ritual',
      type: 'SPA',
      typeLabel: 'SPA и Баня',
      zone: 'spa',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/7fa7a1cdaa60112376a1aa35123825ce.jpg',
      title: 'SPA-ритуал «Тянь-Шань»',
      desc: '90 минут: скраб, обёртывание и массаж с маслами горных трав.',
      meta: [{ ic: 'clock', t: '90 мин' }, { ic: 'star', t: '4.9' }],
      price: '38 000',
      per: 'визит',
      cta: 'Купить',
    },
    {
      id: 'heated-pool',
      type: 'SPA',
      typeLabel: 'Бассейн',
      zone: 'spa',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/b9412961e77379e1beedf84c8108ed65.jpg',
      title: 'Бассейн с подогревом',
      desc: 'Панорамный бассейн, зона отдыха и бар у воды.',
      meta: [{ ic: 'clock', t: '08:00–22:00' }],
      price: '8 000',
      per: 'визит',
      cta: 'Купить',
    },
  ],

  mice: {
    catalogPdf:
      'https://oq-prod.storage.yandexcloud.kz/media-test/7470fffa7dbe305ff8f17936ec7a9faa.pdf',
    calculatorUrl: 'https://oiqaragai.avm8.io/',
    stats: [
      { value: '300+', label: 'гостей' },
      { value: '5', label: 'площадок' },
      { value: '365', label: 'дней в году' },
    ],
    features: [
      {
        n: '01',
        title: 'Конференции и форумы',
        desc: 'Залы на 50–200 человек с техникой, кейтерингом и проживанием.',
      },
      {
        n: '02',
        title: 'Тимбилдинг на склоне',
        desc: 'Активные программы, верёвочные парки и вечерние мероприятия.',
      },
      {
        n: '03',
        title: 'Корпоративы под ключ',
        desc: 'От welcome-кофе до гала-ужина — полный MICE-сервис на курорте.',
      },
    ],
  },

  eventsHub: {
    portals: [
      {
        slug: 'event',
        tag: 'Афиша',
        title: 'Event',
        desc: 'Концерты, фестивали, спорт и семейные активности — предстоящие и архив по календарю.',
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/4ab09cd056b46f8a04eb02a41cc9fdc4.jpg',
        highlights: ['Концерты и фестивали', 'Спортивные события', 'Архив прошедших'],
        cta: 'Смотреть афишу',
      },
      {
        slug: 'corporate',
        tag: 'MICE',
        title: 'Корпоративные',
        desc: 'Площадки для бизнеса: конференции, тимбилдинги и корпоративы в горах.',
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/c625a507521f98262ca3793138f93c1a.png',
        highlights: ['До 300 гостей', 'Кейтеринг и техника', 'Калькулятор бюджета'],
        cta: 'Для бизнеса',
      },
    ],
  },

  eventsEvent: [
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9dc9a54825f5be9e69cc9dfeba062a69.jpg',
      title: 'Новогодняя ночь в горах',
      desc: 'Гала-ужин, живая музыка, фейерверк над склоном и ночное катание до рассвета.',
      date: '31 декабря, 20:00',
      sortDate: '2026-12-31',
      featured: true,
      past: false,
      cta: 'Купить билет',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/4ab09cd056b46f8a04eb02a41cc9fdc4.jpg',
      title: 'Кубок по фрирайду',
      desc: 'Трёхдневные соревнования на закрытых и открытых склонах с призовым фондом.',
      date: '14–16 февраля',
      sortDate: '2026-02-14',
      featured: false,
      past: false,
      cta: 'Купить билет',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/672781f715c9dfff7e6f26a11daef8b6.jpg',
      title: 'Фестиваль «Горный огонь»',
      desc: 'Концерты под открытым небом, фуд-корт и ночное катание.',
      date: '8 марта, 18:00',
      sortDate: '2026-03-08',
      featured: false,
      past: false,
      cta: 'Купить билет',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/21b9d22819c9d8ba4706a448d9ce6ea2.jpeg',
      title: 'Йога на рассвете',
      desc: 'Занятие на смотровой площадке с видом на заснеженные вершины.',
      date: 'Каждую субботу, 07:00',
      sortDate: null,
      featured: false,
      past: false,
      cta: 'Записаться',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f86b7ca3f7e98d67458984dc8c5c7a12.jpg',
      title: 'Гастро-ужин от шефа',
      desc: 'Дегустационное меню из 7 блюд в ресторане «Хвоя» с винной парой.',
      date: '21 февраля, 19:00',
      sortDate: '2026-02-21',
      featured: false,
      past: false,
      cta: 'Забронировать',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/35cbcb290585a502aa92f013e08e63f4.jpg',
      title: 'Детский снежный лагерь',
      desc: 'Недельная программа: лыжи, творческие мастер-классы и прогулки в лесу.',
      date: 'Январь — февраль',
      sortDate: '2026-01-15',
      featured: false,
      past: false,
      cta: 'Подробнее',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/7f023cdfe0db3b829a3434065a344d78.jpg',
      title: 'Осенний гриль-фестиваль',
      desc: 'Открытый огонь, локальные фермеры и живая музыка в долине.',
      date: '12 октября 2025',
      sortDate: '2025-10-12',
      featured: false,
      past: true,
      cta: 'Архив',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9dc9a54825f5be9e69cc9dfeba062a69.jpg',
      title: 'Новый год 2025',
      desc: 'Гала-вечер с диджей-сетом и полуночным салютом над курортом.',
      date: '31 декабря 2024',
      sortDate: '2024-12-31',
      featured: false,
      past: true,
      cta: 'Архив',
    },
  ],

  corporateAll: [
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/c625a507521f98262ca3793138f93c1a.png',
      title: 'Зимний корпоратив',
      desc: 'Площадки MICE до 300 гостей: кейтеринг, техника и тимбилдинг на склоне.',
      date: 'MICE · по запросу',
      cta: 'Запросить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/0804ee613beaed6769b1f1cc114b6c49.jpg',
      title: 'Конференция в горах',
      desc: 'Залы на 50–200 человек, проживание и полный MICE-сервис на курорте.',
      date: 'MICE · круглый год',
      cta: 'Запросить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/672781f715c9dfff7e6f26a11daef8b6.jpg',
      title: 'Тимбилдинг на склоне',
      desc: 'Командные активности, верёвочный парк и вечерняя программа у костра.',
      date: 'MICE · сезонно',
      cta: 'Запросить',
    },
  ],
};
