/* Oi-Qaragai — mock data (structured for future Strapi swap) */
import { enrichOQ } from './i18n/utils.js';

export const RAW_OQ = {
  contacts: {
    phone: '+7 727 312 00 08',
    insta: '@oiqaragai',
    instaUrl: 'https://www.instagram.com/oiqaragai/',
    weather: '+21°C',
    address: 'Алматинская область, ущелье Ой-Карагай',
    email: 'hello@oiqaragai.kz',
    tagline:
      'Всесезонный горный курорт в часе езды от Алматы. Катание, отдых и события круглый год.',
    hours: 'Ежедневно, 08:00 – 23:00',
    copyright: '© 2026 Oi-Qaragai Mountain Resort. Все права защищены.',
  },

  pageHero: {
    guide: 'https://oq-prod.storage.yandexcloud.kz/media-test/672781f715c9dfff7e6f26a11daef8b6.jpg',
    offers: 'https://oq-prod.storage.yandexcloud.kz/media-test/3cbc915db86b87188ea60419d4c0b89b.jpg',
    eventsHub:
      'https://oq-prod.storage.yandexcloud.kz/media-test/43106cfb26654a76378784357a96c007.jpg',
    eventAfisha:
      'https://oq-prod.storage.yandexcloud.kz/media-test/4ab09cd056b46f8a04eb02a41cc9fdc4.jpg',
    corporate:
      'https://oq-prod.storage.yandexcloud.kz/media-test/c625a507521f98262ca3793138f93c1a.png',
  },

  offersMeta: {
    priceFrom: '6 000 ₸',
    maxDiscount: '−25%',
  },

  app: {
    screenshots: [
      {
        src: 'https://oq-prod.storage.yandexcloud.kz/media-test/ddfe930402657241d67d1a1bb8df9f74.png',
        alt: 'Карта и поиск в приложении Oi-Qaragai',
      },
      {
        src: 'https://oq-prod.storage.yandexcloud.kz/media-test/b4df8c0b866314d81c1a46bd7363f236.png',
        alt: 'SkiPass и сервисы в приложении Oi-Qaragai',
      },
    ],
    stores: {
      ios: {
        url: 'https://apps.apple.com/kz/app/oi-qaragai-mountain-resort/id6446198193',
        icon: 'https://oq-prod.storage.yandexcloud.kz/media-test/dd23f8ee3a5364215a63a5766f120c17.svg',
        label: 'App Store',
      },
      android: {
        url: 'https://play.google.com/store/apps/details?id=kz.qaragai&_gl=1*1mop7rc*_gcl_au*MTYwODQzMTU5OS4xNzgwOTk3MDgz',
        icon: 'https://oq-prod.storage.yandexcloud.kz/media-test/4b310ad591a3ea4e8bcf8cb4d9db02db.svg',
        label: 'Google Play',
      },
    },
  },

  weather: {
    city: {
      name: 'Алматы',
      temp: '26°C',
      condition: 'Облачно',
      day: 'пятница',
      wind: '8 км/ч',
      humidity: '40%',
      precipitation: '20%',
      icon: 'cloud',
    },
    resort: {
      name: 'Курорт',
      temp: '21°C',
      condition: 'Небольшой дождь',
      day: 'пятница',
      wind: '10 км/ч',
      humidity: '52%',
      precipitation: '35%',
      icon: 'rain',
      open: true,
      lifts: '12/14',
      slopes: '18/22',
    },
    forecast: [
      { day: 'Сегодня', city: '26°', resort: '21°', icon: 'rain' },
      { day: 'Сб', city: '27°', resort: '22°', icon: 'sun' },
      { day: 'Вс', city: '28°', resort: '23°', icon: 'sun' },
      { day: 'Пн', city: '25°', resort: '19°', icon: 'cloud' },
      { day: 'Вт', city: '24°', resort: '18°', icon: 'cloud' },
      { day: 'Ср', city: '26°', resort: '20°', icon: 'sun' },
      { day: 'Чт', city: '27°', resort: '21°', icon: 'sun' },
    ],
  },

  mega: [
    {
      key: 'hotels',
      title: 'Отели',
      icon: 'bed',
      items: [
        'Домики на деревьях',
        'VIP-шале «Четыре Силы»',
        'Отель «Aq-Qaiyn»',
        'Глэмпинги TAU TYNYS',
        'Коттеджи класса LUX',
      ],
      more: 'Все варианты размещения',
    },
    {
      key: 'fun',
      title: 'Развлечения',
      icon: 'ski',
      items: [
        'Конный центр',
        'Верёвочный «Парк Приключений»',
        'Троллейный парк',
        'Тюбинг',
        'Пешие туры',
        'Aport Coaster',
      ],
      more: 'Все активности',
    },
    {
      key: 'rest',
      title: 'Рестораны',
      icon: 'fork',
      items: [
        '«Aport-Alatau»',
        '«Чашнагири»',
        '«Ак-Ауыл»',
        '«Eighteen-twenty 1820»',
        'DoneRoll',
      ],
      more: 'Все рестораны',
    },
    {
      key: 'spa',
      title: 'SPA и Баня',
      icon: 'spa',
      items: [
        'Этно-SPA «UMAI»',
        'Горный Рассвет',
        'Эверест',
        'Медовый рай',
        'СПА «Воздух»',
      ],
      more: 'Все услуги SPA',
    },
    {
      key: 'events',
      title: 'Мероприятия',
      icon: 'star',
      items: [
        'Афиша событий',
        'Новый год в горах',
        'Свадьбы',
        'Концерты',
        'Прошедшие события',
      ],
      more: 'Вся афиша',
    },
    {
      key: 'biz',
      title: 'Для бизнеса',
      icon: 'briefcase',
      items: [
        'MICE / Конференции',
        'Тимбилдинг',
        'Калькулятор мероприятия',
        'Кейтеринг',
        'MICE-каталог (PDF)',
      ],
      more: 'Возможности курорта',
    },
  ],

  quick: [
    { t: 'Проживание', d: '8 объектов', icon: 'bed', href: '/guide' },
    { t: 'Рестораны', d: '15 заведений', icon: 'fork', href: '/guide' },
    { t: 'Активности', d: 'круглый год', icon: 'ski', href: '/guide' },
    { t: 'Веб-камеры', d: '6 трансляций', icon: 'camera', href: '#' },
    { t: '3D-тур', d: 'карта курорта', icon: 'cube', href: '#' },
  ],

  hero: {
    slides: [
      {
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e94707741a500180a04f7678d1fc84cb.jpg',
        title: 'Облако нежности',
        detail: 'SPA-программы и отдых в горах',
        href: '/offers',
      },
      {
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/b9412961e77379e1beedf84c8108ed65.jpg',
        title: 'All Inclusive',
        detail: '8 объектов размещения на курорте',
        href: '/guide',
      },
      {
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/a60880837954b3f599fa9bf993e716bd.jpg',
        title: 'Развлечения',
        detail: 'троллей, тюбинг, верёвочный парк и многое другое',
        href: '/guide',
      },
      {
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/43106cfb26654a76378784357a96c007.jpg',
        title: 'Детский лагерь 2026',
        detail: 'летняя программа для детей в горах',
        href: '/events',
      },
    ],
    interval: 5500,
  },

  gallery: [
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/624e0b4b4e408bcd06cc361ac97272d7.jpg', cap: 'Домики на деревьях', tall: true },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e87983b27c8a754c2306e9bf7ff4661d.jpg', cap: 'VIP-шале «Четыре Силы»' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/672781f715c9dfff7e6f26a11daef8b6.jpg', cap: 'Глэмпинги TAU TYNYS' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/35cbcb290585a502aa92f013e08e63f4.jpg', cap: 'Отель «Aq-Qaiyn»' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/3cbc915db86b87188ea60419d4c0b89b.jpg', cap: 'Троллейный парк' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/21b9d22819c9d8ba4706a448d9ce6ea2.jpeg', cap: 'Этно-SPA «UMAI»', tall: true },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f86b7ca3f7e98d67458984dc8c5c7a12.jpg', cap: 'Panorama Plaza' },
    { img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f495ef49c03361c11965fd30bc01f864.jpg', cap: '«Aport-Alatau»' },
  ],

  rules: [
    {
      title: 'Регистрация и заезд',
      body: 'Заезд с 14:00, выезд до 12:00. При заселении необходим документ, удостоверяющий личность. Ранний заезд и поздний выезд — по предварительному запросу и при наличии свободных номеров.',
    },
    {
      title: 'Безопасность на склонах',
      body: 'Катание разрешено только на подготовленных трассах в рабочие часы подъёмников. Шлем обязателен для детей до 14 лет и рекомендован всем гостям. Следуйте указателям и сигналам службы спасения курорта.',
    },
    {
      title: 'Прокат снаряжения',
      body: 'Прокат лыж, сноубордов и защиты доступен у нижней станции с 08:30. Залог оформляется картой или наличными. Снаряжение необходимо вернуть в день окончания аренды до 22:00.',
    },
    {
      title: 'Размещение с животными',
      body: 'Мы рады гостям с питомцами в отдельных шале категории Pet-friendly. Необходимо предупредить администратора при бронировании. На территории действует правило выгула на поводке.',
    },
    {
      title: 'Парковка и трансфер',
      body: 'Бесплатная гостевая парковка расположена у въезда на курорт. Трансфер от Алматы и обратно доступен по расписанию — бронируйте место заранее на стойке размещения или по телефону.',
    },
  ],

  partners: ['KASPI', 'Visa', 'Air Astana', 'Beeline', 'Halyk', 'Almaty'],

  offersAll: [
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/3cbc915db86b87188ea60419d4c0b89b.jpg',
      badge: '16+',
      badgeType: 'accent',
      tag: 'Пакет',
      category: 'Пакеты',
      title: 'Комбо приключений 16+',
      desc: 'Троллейный парк, верёвочный парк «Весёлый» и подъём на канатной дороге.',
      price: '24 700',
      per: 'пакет',
      cta: 'Купить',
      homeFeatured: true,
      homeOrder: 1,
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/d9ff5933bc01ef69be93b99a16304d28.jpg',
      badge: '16+',
      badgeType: 'accent',
      tag: 'Пакет',
      category: 'Пакеты',
      title: 'Экстремальный максимум 16+',
      desc: 'Aport Coaster, троллейный парк, верёвочный парк и другие экстремальные активности.',
      price: '44 000',
      per: 'пакет',
      cta: 'Купить',
      homeFeatured: true,
      homeOrder: 3,
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/43a66e0452a52f1ed4468100af36e268.jpg',
      badge: '10+',
      badgeType: 'dark',
      tag: 'Пакет',
      category: 'Пакеты',
      title: 'Меткое комбо 10+',
      desc: 'Стрельба из лука 15 минут и стрельба в тире — 21 выстрел.',
      price: '6 000',
      per: 'пакет',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9a6a519d6634f0ae6a476bf939a100a7.png',
      badge: 'SPA',
      badgeType: 'accent',
      tag: 'Релакс',
      category: 'SPA',
      title: 'Горный Рассвет',
      desc: 'SPA-процедуры на двоих с видом на горные вершины.',
      price: '85 000',
      per: 'за визит',
      cta: 'Купить',
      homeFeatured: true,
      homeOrder: 2,
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/749902c79c433054f6de29d71fa1cb4f.jpg',
      badge: 'SPA',
      badgeType: 'dark',
      tag: 'Релакс',
      category: 'SPA',
      title: 'Эверест',
      desc: 'Пакет SPA-процедур, вдохновлённый духом Эвереста и восхождением на вершину.',
      price: '53 000',
      per: 'за визит',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/b1f11782a8a8b0ed4453e6386a9f83e1.jpg',
      badge: 'SPA',
      badgeType: 'dark',
      tag: 'Релакс',
      category: 'SPA',
      title: 'Медовый рай',
      desc: 'Роскошные уходы и SPA-процедуры в программе «Медовый рай».',
      price: '53 000',
      per: 'за визит',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/ded91824f2e3fd3d46c60f1b3d16bd59.jpg',
      badge: 'SPA',
      badgeType: 'dark',
      tag: 'Массаж',
      category: 'SPA',
      title: 'Королевский массаж (в 4 руки)',
      desc: 'Массаж в четыре руки продолжительностью 60 минут.',
      price: '50 000',
      per: 'за визит',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/69dfc7138383d8f658b9ea84a04b14aa.jpg',
      badge: 'SPA',
      badgeType: 'dark',
      tag: 'Релакс',
      category: 'SPA',
      title: 'СПА «Воздух»',
      desc: 'Хаммам, ароматерапия и расслабляющие процедуры.',
      price: '42 000',
      per: 'за визит',
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/60f3caaafaf55aa0304b73b6fd9dabde.jpg',
      badge: 'Активность',
      badgeType: 'accent',
      tag: 'Парк',
      category: 'Активности',
      title: 'Верёвочный «Парк Приключений»',
      desc: 'Маршруты разного уровня сложности на свежем воздухе в горах.',
      price: '5 000',
      per: 'билет',
      cta: 'Купить',
    },
  ],

  mapZones: [
    { id: 'all', label: 'Весь курорт', icon: 'cube', x: 50, y: 50 },
    { id: 'hotels', label: 'Проживание', icon: 'bed', x: 28, y: 62 },
    { id: 'rest', label: 'Рестораны', icon: 'fork', x: 58, y: 38 },
    { id: 'fun', label: 'Активности', icon: 'ski', x: 72, y: 58 },
    { id: 'spa', label: 'SPA и баня', icon: 'spa', x: 42, y: 28 },
  ],

  thingsAll: [
    {
      id: 'terrenkur',
      type: 'Отели',
      typeLabel: 'Отель',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/624e0b4b4e408bcd06cc361ac97272d7.jpg',
      title: 'Домики на деревьях',
      desc: 'Уникальное проживание под кронами сосен с тёплыми полами и всем необходимым для отдыха.',
      meta: [{ ic: 'user', t: 'до 4 гостей' }, { ic: 'bed', t: 'эко-номер' }],
      price: '65 000',
      per: 'ночь',
      cta: 'Подробнее',
      homeFeatured: true,
      homeOrder: 1,
    },
    {
      id: 'pine-peak',
      type: 'Отели',
      typeLabel: 'Шале',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e87983b27c8a754c2306e9bf7ff4661d.jpg',
      title: 'VIP-шале «Четыре Силы»',
      desc: 'Двухэтажные VIP-шале для компании до 10 гостей с панорамными видами на Тянь-Шань.',
      meta: [{ ic: 'user', t: 'до 10 гостей' }, { ic: 'star', t: 'VIP' }],
      price: '512 000',
      per: 'ночь',
      cta: 'Подробнее',
      homeFeatured: true,
      homeOrder: 2,
    },
    {
      id: 'glamping-hvoya',
      type: 'Отели',
      typeLabel: 'Глэмпинг',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/672781f715c9dfff7e6f26a11daef8b6.jpg',
      title: 'Глэмпинги TAU TYNYS',
      desc: '14 домиков на высоте 2140 м с панорамными видами на плато Aqtas.',
      meta: [{ ic: 'user', t: '2 гостя' }, { ic: 'bed', t: 'глэмпинг' }],
      price: '86 400',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      type: 'Отели',
      typeLabel: 'Отель',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/35cbcb290585a502aa92f013e08e63f4.jpg',
      title: 'Отель «Aq-Qaiyn»',
      desc: 'Горный отель 4⭐ с 18 номерами в европейском стиле в живописном районе курорта.',
      meta: [{ ic: 'star', t: '4⭐' }, { ic: 'user', t: '2 гостя' }],
      price: '46 400',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      type: 'Отели',
      typeLabel: 'Коттедж',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9a60783bba91ce5c5d98cc36d40a5c4c.jpg',
      title: 'Коттеджи класса LUX',
      desc: 'Роскошные коттеджи с потрясающими видами из больших окон и балконов.',
      meta: [{ ic: 'user', t: 'семья' }, { ic: 'bed', t: 'LUX' }],
      price: '46 400',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      type: 'Отели',
      typeLabel: 'Этно-отель',
      zone: 'hotels',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/6a4d384a3852129dff54c430020bb333.jpg',
      title: 'Этно-Отель «Орман-Ауылы»',
      desc: 'Шесть юрт в сосновом лесу — аутентичный отдых с современным комфортом.',
      meta: [{ ic: 'user', t: 'компания' }, { ic: 'bed', t: 'юрта' }],
      price: '58 400',
      per: 'ночь',
      cta: 'Подробнее',
    },
    {
      id: 'ochag',
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      zone: 'rest',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f495ef49c03361c11965fd30bc01f864.jpg',
      title: '«Aport-Alatau» Горный гриль-ресторан',
      desc: 'Мясо на открытом огне у подножия гор — любимая точка после активного дня.',
      meta: [{ ic: 'clock', t: '09:00–20:00' }, { ic: 'fork', t: 'Гриль' }],
      cta: 'Меню',
      homeFeatured: true,
      homeOrder: 3,
    },
    {
      id: 'hvoya',
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      zone: 'rest',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/bce371d31522550313a3609f002f16ee.jpeg',
      title: '«Чашнагири»',
      desc: 'Царская грузинская кухня: хинкали, хачапури и ароматы специй.',
      meta: [{ ic: 'clock', t: '11:00–22:00' }, { ic: 'fork', t: 'Грузинская' }],
      cta: 'Меню',
      homeFeatured: true,
      homeOrder: 4,
    },
    {
      id: 'panorama',
      type: 'Рестораны',
      typeLabel: 'Банкетный зал',
      zone: 'rest',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f86b7ca3f7e98d67458984dc8c5c7a12.jpg',
      title: 'Банкетный зал «Panorama Plaza»',
      desc: 'Зал до 250 персон для свадеб, корпоративов и торжественных вечеров.',
      meta: [{ ic: 'user', t: 'до 250 гостей' }],
      cta: 'Меню',
    },
    {
      id: 'aqauyl',
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      zone: 'rest',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/29ef5ff1881c319432da35984ffbdc5b.jpeg',
      title: '«Ак-Ауыл»',
      desc: 'Национальная кухня в роскошной казахской юрте с атмосферой колорита.',
      meta: [{ ic: 'clock', t: '11:00–22:00' }, { ic: 'fork', t: 'Национальная' }],
      cta: 'Меню',
    },
    {
      type: 'Рестораны',
      typeLabel: 'Ресторан',
      zone: 'rest',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/ed6abc9b21d69410ad627f6d65cdd75d.jpeg',
      title: '«Eighteen-twenty 1820»',
      desc: 'Высокогорный ресторан: мясо в хоспере и классические блюда азиатской кухни.',
      meta: [{ ic: 'clock', t: '09:30–21:30' }],
      cta: 'Меню',
    },
    {
      id: 'ski-pass',
      type: 'Развлечения',
      typeLabel: 'Активность',
      zone: 'fun',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/be9de408fd6866bd1150c6b786569c94.jpg',
      title: 'Конный центр (Aport Plaza)',
      desc: 'Прогулки верхом по живописным окрестностям с профессиональными инструкторами.',
      meta: [{ ic: 'user', t: 'для всей семьи' }],
      price: '5 000',
      per: 'билет',
      cta: 'Купить',
      homeFeatured: true,
      homeOrder: 5,
    },
    {
      id: 'zipline',
      type: 'Развлечения',
      typeLabel: 'Активность',
      zone: 'fun',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/dc09954344ceef7c8730400ad93dd82d.jpg',
      title: 'Пешие туры',
      desc: 'Оборудованные тропы и маршруты с гидами по живописным местам ущелья.',
      meta: [{ ic: 'user', t: 'для всей семьи' }],
      price: '4 000',
      per: 'билет',
      cta: 'Купить',
      homeFeatured: true,
      homeOrder: 6,
    },
    {
      id: 'tubing',
      type: 'Развлечения',
      typeLabel: 'Активность',
      zone: 'fun',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/4ea85f24244269f7faaa0056395050ac.png',
      title: 'Тюбинг',
      desc: 'Катание на тюбингах по подготовленным трассам с бугельным подъёмником.',
      meta: [{ ic: 'user', t: 'для всей семьи' }],
      price: '1 500',
      per: 'билет',
      cta: 'Купить',
    },
    {
      type: 'Развлечения',
      typeLabel: 'Активность',
      zone: 'fun',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/3cbc915db86b87188ea60419d4c0b89b.jpg',
      title: 'Троллейный парк',
      desc: 'Захватывающее приключение на свежем воздухе — отличный способ побороть страх высоты.',
      meta: [{ ic: 'user', t: '16+' }],
      price: '7 000',
      per: 'билет',
      cta: 'Купить',
    },
    {
      id: 'adventure-park',
      type: 'Развлечения',
      typeLabel: 'Активность',
      zone: 'fun',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/60f3caaafaf55aa0304b73b6fd9dabde.jpg',
      title: 'Верёвочный «Парк Приключений»',
      desc: 'Маршруты разного уровня сложности для взрослых и детей в горах.',
      meta: [{ ic: 'user', t: 'для всей семьи' }],
      price: '5 000',
      per: 'билет',
      cta: 'Купить',
    },
    {
      id: 'cedar-bath',
      type: 'SPA',
      typeLabel: 'SPA и Баня',
      zone: 'spa',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/21b9d22819c9d8ba4706a448d9ce6ea2.jpeg',
      title: 'Этно-SPA «UMAI» и Баня',
      desc: 'SPA и банные ритуалы в традиционных казахских юртах.',
      meta: [{ ic: 'clock', t: 'по записи' }],
      cta: 'Купить',
      homeFeatured: true,
      homeOrder: 7,
    },
    {
      id: 'tianshan-ritual',
      type: 'SPA',
      typeLabel: 'SPA и Баня',
      zone: 'spa',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/9a6a519d6634f0ae6a476bf939a100a7.png',
      title: 'Горный Рассвет',
      desc: 'Пакет SPA-процедур на двоих с видом на горные вершины.',
      meta: [{ ic: 'clock', t: 'по записи' }, { ic: 'user', t: 'на двоих' }],
      price: '85 000',
      per: 'визит',
      cta: 'Купить',
      homeFeatured: true,
      homeOrder: 8,
    },
    {
      id: 'heated-pool',
      type: 'SPA',
      typeLabel: 'SPA',
      zone: 'spa',
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/69dfc7138383d8f658b9ea84a04b14aa.jpg',
      title: 'СПА «Воздух»',
      desc: 'Хаммам, ароматерапия и расслабляющие процедуры в SPA-зоне курорта.',
      meta: [{ ic: 'clock', t: 'по записи' }],
      price: '42 000',
      per: 'визит',
      cta: 'Купить',
    },
  ],

  mice: {
    catalogPdf:
      'https://oq-prod.storage.yandexcloud.kz/media-test/7470fffa7dbe305ff8f17936ec7a9faa.pdf',
    calculatorUrl: 'https://oiqaragai.avm8.io/',
    stats: [
      { value: '300+', label: 'гостей' },
      { value: '5', label: 'площадок' },
      { value: '365', label: 'дней в году' },
    ],
    features: [
      {
        n: '01',
        title: 'Конференции и форумы',
        desc: 'Залы на 50–200 человек с техникой, кейтерингом и проживанием.',
      },
      {
        n: '02',
        title: 'Тимбилдинг на склоне',
        desc: 'Активные программы, верёвочные парки и вечерние мероприятия.',
      },
      {
        n: '03',
        title: 'Корпоративы под ключ',
        desc: 'От welcome-кофе до гала-ужина — полный MICE-сервис на курорте.',
      },
    ],
  },

  eventsHub: {
    portals: [
      {
        slug: 'event',
        tag: 'Афиша',
        title: 'Event',
        desc: 'Концерты, фестивали, спорт и семейные активности — предстоящие и архив по календарю.',
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/4ab09cd056b46f8a04eb02a41cc9fdc4.jpg',
        highlights: ['Концерты и фестивали', 'Спортивные события', 'Архив прошедших'],
        cta: 'Смотреть афишу',
      },
      {
        slug: 'corporate',
        tag: 'MICE',
        title: 'Корпоративные',
        desc: 'Площадки для бизнеса: конференции, тимбилдинги и корпоративы в горах.',
        img: 'https://oq-prod.storage.yandexcloud.kz/media-test/c625a507521f98262ca3793138f93c1a.png',
        highlights: ['До 300 гостей', 'Кейтеринг и техника', 'Калькулятор бюджета'],
        cta: 'Для бизнеса',
      },
    ],
  },

  eventsEvent: [
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/43106cfb26654a76378784357a96c007.jpg',
      title: 'Детский лагерь 2026',
      desc: 'Летняя программа для детей в горах: активности, творчество и прогулки на природе.',
      date: 'Лето 2026',
      sortDate: '2026-06-01',
      featured: true,
      past: false,
      cta: 'Подробнее',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f87d98a1e20682257a3ef1b94f56ec80.jpg',
      title: 'Небесные качели',
      desc: 'Высокогорное развлечение на высоте 2140 м — ощущение полёта над пропастью на Aqtas.',
      date: 'Круглый год',
      sortDate: null,
      featured: false,
      homeSide: true,
      past: false,
      cta: 'Купить билет',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/3cbc915db86b87188ea60419d4c0b89b.jpg',
      title: 'Комбо приключений 16+',
      desc: 'Троллейный парк, верёвочный парк и подъём на канатной дороге в одном пакете.',
      date: 'Круглый год',
      sortDate: null,
      featured: false,
      past: false,
      cta: 'Купить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/21b9d22819c9d8ba4706a448d9ce6ea2.jpeg',
      title: 'Этно-SPA «UMAI»',
      desc: 'Банные ритуалы и SPA-процедуры в традиционных казахских юртах.',
      date: 'По записи',
      sortDate: null,
      featured: false,
      past: false,
      cta: 'Записаться',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/f86b7ca3f7e98d67458984dc8c5c7a12.jpg',
      title: 'Свадьбы в Panorama Plaza',
      desc: 'Банкетный зал до 250 персон с панорамными видами для торжественных мероприятий.',
      date: 'По бронированию',
      sortDate: null,
      featured: false,
      past: false,
      cta: 'Забронировать',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/e94707741a500180a04f7678d1fc84cb.jpg',
      title: 'Облако нежности',
      desc: 'SPA-программа для расслабления и восстановления в горах.',
      date: 'По записи',
      sortDate: null,
      featured: false,
      past: false,
      cta: 'Записаться',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/4ab09cd056b46f8a04eb02a41cc9fdc4.jpg',
      title: 'Концерты и фестивали',
      desc: 'Афиша событий курорта: музыка, спорт и семейные активности.',
      date: 'Архив 2025',
      sortDate: '2025-08-01',
      featured: false,
      past: true,
      cta: 'Архив',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/c625a507521f98262ca3793138f93c1a.png',
      title: 'Корпоративные мероприятия',
      desc: 'MICE-площадки, тимбилдинг и банкеты для бизнеса в горах.',
      date: 'Архив 2025',
      sortDate: '2025-12-01',
      featured: false,
      past: true,
      cta: 'Архив',
    },
  ],

  corporateAll: [
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/c625a507521f98262ca3793138f93c1a.png',
      title: 'Корпоратив в горах',
      desc: 'Площадки MICE до 300 гостей: кейтеринг, техника и тимбилдинг на курорте.',
      date: 'MICE · по запросу',
      cta: 'Запросить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/0804ee613beaed6769b1f1cc114b6c49.jpg',
      title: 'Конференция в горах',
      desc: 'Залы на 50–200 человек, проживание и полный MICE-сервис на курорте.',
      date: 'MICE · круглый год',
      cta: 'Запросить',
    },
    {
      img: 'https://oq-prod.storage.yandexcloud.kz/media-test/672781f715c9dfff7e6f26a11daef8b6.jpg',
      title: 'Тимбилдинг на склоне',
      desc: 'Командные активности, верёвочный парк и вечерняя программа у костра.',
      date: 'MICE · сезонно',
      cta: 'Запросить',
    },
  ],

  profile: {
    user: {
      name: 'Айгуль Нурланова',
      email: 'aigul.n@mail.kz',
      phone: '+7 701 234 56 78',
      initials: 'АН',
      tier: 'Gold',
      tierLabel: 'Gold Member',
      points: 2840,
      nights: 12,
      memberSince: '2023',
      avatar: null,
    },
    wallet: {
      deposit: {
        balance: 48500,
        lastTopUp: '28 ноя 2025',
        lastAmount: '20 000',
      },
      skiPass: {
        offerTitle: 'Комбо приключений 16+',
        status: 'active',
        statusLabel: 'Активен',
        validFrom: '8 июн 2026',
        validTo: '8 июн 2026',
        daysLeft: 1,
        totalDays: 1,
        passNumber: 'PK-28491',
      },
    },
    bookings: [
      {
        id: 'bk-1',
        offerTitle: 'Комбо приключений 16+',
        status: 'confirmed',
        statusLabel: 'Подтверждено',
        dates: '8 июн 2026',
        guests: 2,
        total: '24 700',
      },
      {
        id: 'bk-2',
        thingId: 'terrenkur',
        status: 'upcoming',
        statusLabel: 'Предстоит',
        dates: '15–17 июн 2026',
        guests: 4,
        total: '195 000',
      },
      {
        id: 'bk-3',
        offerTitle: 'Горный Рассвет',
        status: 'completed',
        statusLabel: 'Завершено',
        dates: '22 мая 2026',
        guests: 2,
        total: '85 000',
      },
    ],
    favorites: [
      { id: 'fav-1', thingId: 'pine-peak' },
      { id: 'fav-2', thingId: 'zipline' },
      { id: 'fav-3', thingId: 'cedar-bath' },
    ],
  },
};

export const OQ = enrichOQ(RAW_OQ);
